Add dockerignore
dial-once/docker-crons pull request #11
Opened 2017-07-25 11:45 UTC by Spring3

Per [#142](https://github.com/dial-once/chores/issues/142)

2017-07-25 11:47 UTC, ykhatal approved these changes

2017-07-25 16:20 UTC, jkernech requested changes
The file can be cleanup a bit since there is nothing related to nodejs in this repo

2017-07-25 20:06 UTC, mrister approved these changes

2017-07-26 09:39 UTC, jkernech approved these changes

2017-07-26 18:15 UTC, ofkindness approved these changes

2017-07-27 06:45 UTC, williamluang approved these changes

2017-07-31 13:29 UTC, merged